name: CI/CD Server Workflow

env:
  SERVER_IP: '54.37.71.166'
  SERVER_USER: 'root'

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: install dependencies
        run: npm ci .npm --prefer-offline

      - name: check linting code
        run: npm run lint

      # - name: check dependencies vulnerability
      #   run: npm audit

      - name: test execution
        run: npm run test:ci
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
